apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  annotations:
    volume.beta.kubernete.io/storage-class: "standard"
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
